spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  liquibase:
    enabled: false
  application:
    name: soddexporter
  server:
    port: 8090
  jpa:
    hibernate:
      ddl-auto: update

  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/soddExporter
  #    username: postgres
  #    password: root
  datasource:
    url: jdbc:h2:file:./data/demo-db   # file-based, relative to project root
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect
