spring:
  h2:
    console:
      enabled: true
  liquibase:
    enabled: false
  application:
    name: soddexporter
  server:
    port: 8090
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5432/soddExporter
    username: postgres
    password: root
